# Generated by Django 3.0.6 on 2020-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together={('order', 'question')},
        ),
    ]
